- hosts: all
  name: Autoconverted job legacy-swift-dsvm-functional from old job gate-swift-dsvm-functional-ubuntu-xenial-nv
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export FUNCTEST_TIMEOUT=30
          # Disable all services
          export DEVSTACK_GATE_NO_SERVICES=1
          # Add only what we want, keystone + swift
          export DEVSTACK_GATE_SWIFT=1
          export DEVSTACK_GATE_KEYSTONE=1
          # Need to override default which is neutron enabled
          export DEVSTACK_GATE_NEUTRON=0
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_EXERCISES=0
          export DEVSTACK_GATE_INSTALL_TESTONLY=1
          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi
          if [ "" == "-identity-v3-only" ] ; then
              export DEVSTACK_LOCAL_CONFIG="ENABLE_IDENTITY_V2=False"
          fi

          function post_test_hook {
              cd /opt/stack/new/swift
              # Launch V2 auth tests and v1 tests after.
              sudo -H -u stack timeout -s 9 ${FUNCTEST_TIMEOUT}m tox -e func && \
                  sudo -H -u stack SWIFT_TEST_CONFIG_FILE=/opt/stack/new/swift/test/sample.conf \
                      timeout -s 9 ${FUNCTEST_TIMEOUT}m tox -e func
          }
          export -f post_test_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
